# Generated by Django 3.2.5 on 2021-08-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210814_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identity_code',
            field=models.CharField(max_length=10),
        ),
    ]
