# Generated by Django 3.2.5 on 2021-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
