# Generated by Django 3.2.5 on 2021-08-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_account_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
