# Generated by Django 3.2.5 on 2021-08-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='transaction_amount',
            new_name='transfer_amount',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='transaction_destination',
            new_name='transfer_destination',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='transaction_source',
            new_name='transfer_source',
        ),
    ]
