# Generated by Django 3.2.5 on 2021-08-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_auto_20210817_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='account_amount',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
