# Generated by Django 3.2.5 on 2021-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0003_history_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='transfer_amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
